#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
#define _BASE 0
#define _GAME 1
#define _FLIP 2
#define _FAUDIO 3
#define _RGBMOUSE 4

enum {
    TD_COPY_PASTE,
    TD_SHIFT_GUI,
};

qk_tap_dance_action_t tap_dance_actions[] = {
    [TD_COPY_PASTE] = ACTION_TAP_DANCE_DOUBLE(LCTL(KC_INS), LSFT(KC_INS)),
};

enum custom_keycodes {
  CPS_DEL = SAFE_RANGE,
  CPS_ENT
};

/*#define L4_HOME LT(4, KC_HOME)*/
/*#define L4_PGDN LT(4, KC_PGDN)*/
#define L3_RBRC LT(3, KC_RBRC)
#define L2_ENT LT(2, KC_ENT)
#define SF_GUI LSFT(KC_LGUI)
#define SFT_SPC RSFT_T(KC_SPC)
#define SFT_BSP LSFT_T(KC_BSPC)
#define KT_COPA TD(TD_COPY_PASTE)
#define L4_COMM LT(4, KC_COMM)
#define CTL_TAB LCTL_T(KC_TAB)

const uint16_t PROGMEM f12_combo[] = {KC_Y, KC_U, COMBO_END};
const uint16_t PROGMEM sft_ins_combo[] = {KC_4, KC_5, COMBO_END};
const uint16_t PROGMEM alt_f4_combo[] = {KC_E, KC_R, KC_T, COMBO_END};
const uint16_t PROGMEM ctrl_c_combo[] = {KC_1, KC_2, COMBO_END};
const uint16_t PROGMEM sctl_c_combo[] = {KC_1, KC_2, KC_3, COMBO_END};
combo_t key_combos[COMBO_COUNT] = {
    COMBO(f12_combo, KC_F12),
    COMBO(sft_ins_combo, LSFT(KC_INS)),
    COMBO(alt_f4_combo, LSG(KC_Q)),
    COMBO(ctrl_c_combo, LCTL(KC_R)),
    COMBO(sctl_c_combo, LCTL(LSFT(KC_R))),
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
     static uint16_t my_hash_timer;
    switch (keycode) {

    case KC_DEL:
        if ( ((get_mods() & MOD_MASK_SHIFT) || (get_mods() & MOD_MASK_CTRL)) && !(get_mods() & MOD_MASK_ALT)) {
            if (record->event.pressed) {
                register_code(KC_INS);
            } else {
                unregister_code(KC_INS);
            }
        }
        return false;
//TODO use tap dance advanced like four function td https://web.archive.org/web/20210906183733/https://beta.docs.qmk.fm/using-qmk/software-features/feature_tap_dance
    case CPS_DEL:
        if(record->event.pressed) {
        my_hash_timer = timer_read();
            register_code(KC_CAPS); // Change the key to be held here
          } else {
            unregister_code(KC_CAPS); // Change the key that was held here, too!
            if (timer_elapsed(my_hash_timer) < TAPPING_TERM) {
              SEND_STRING(SS_TAP(X_DEL)); // Change the character(s) to be sent on tap here
            }
      }
      return false;
    
    case CPS_ENT:
        if(record->event.pressed) {
        my_hash_timer = timer_read();
            register_code(KC_CAPS); // Change the key to be held here
          } else {
            unregister_code(KC_CAPS); // Change the key that was held here, too!
            if (timer_elapsed(my_hash_timer) < TAPPING_TERM) {
              SEND_STRING(SS_TAP(X_ENT)); // Change the character(s) to be sent on tap here
            }
      }
      return false;

    }
    return true;
};


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[_BASE] = LAYOUT(
        //┌────────┬────────┬────────┬────────┬────────┬────────┐                                           ┌────────┬────────┬────────┬────────┬────────┬────────┐
           KC_GRV  ,KC_1    ,KC_2    ,KC_3    ,KC_4    ,KC_5    ,                                            KC_6    ,KC_7    ,KC_8    ,KC_9    ,KC_0    ,KC_MINS ,
        //├────────┼────────┼────────┼────────┼────────┼────────┼────────┐                         ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┤
           KC_TAB  ,KC_Q    ,KC_W    ,KC_E    ,KC_R    ,KC_T    ,KC_ESC  ,                          KC_PSCR ,KC_Y    ,KC_U    ,KC_I    ,KC_O    ,KC_P    ,KC_EQL  ,
        //├────────┼────────┼────────┼────────┼────────┼────────┼────────┤                         ├────────┼────────┼────────┼────────┼────────┼────────┼────────┤
           KC_CAPS ,KC_A    ,KC_S    ,KC_D    ,KC_F    ,KC_G    ,KC_NO   ,                          KC_NO   ,KC_H    ,KC_J    ,KC_K    ,KC_L    ,KC_SCLN ,KC_NUHS ,
        //├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┐       ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
           KC_LSFT ,KC_Z    ,KC_X    ,KC_C    ,KC_V    ,KC_B    ,KC_CAPS ,KC_NO   ,        KC_NO   ,KC_NUHS ,KC_N    ,KC_M    ,KC_LBRC ,KC_QUOT ,KC_SLSH ,KC_RSFT ,
        //├────────┼────────┼────────┼────────┼────┬───┴────┬───┼────────┼────────┤       ├────────┼────────┼───┬────┴───┬────┼────────┼────────┼────────┼────────┤
           MO(3)   ,KC_NUBS ,KC_LALT ,KC_LGUI ,     CTL_TAB ,    SFT_BSP ,CPS_DEL  ,        CPS_ENT  ,SFT_SPC ,    TT(1)   ,     L4_COMM ,KC_DOT  ,KC_RALT ,L3_RBRC
        //└────────┴────────┴────────┴────────┘    └────────┘   └────────┴────────┘       └────────┴────────┘   └────────┘    └────────┴────────┴────────┴────────┘
           ),
    [_GAME] = LAYOUT(
        //┌────────┬────────┬────────┬────────┬────────┬────────┐                                           ┌────────┬────────┬────────┬────────┬────────┬────────┐
           KC_TRNS ,KC_TRNS ,KC_TRNS ,KC_TRNS ,KC_TRNS ,KC_TRNS ,                                            KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,
        //├────────┼────────┼────────┼────────┼────────┼────────┼────────┐                         ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┤
           KC_TRNS ,KC_TRNS ,KC_TRNS ,KC_TRNS ,KC_TRNS ,KC_TRNS ,KC_TRNS ,                          KC_NO   ,KC_NO   ,KC_PGUP ,KC_UP   ,KC_PGDN ,KC_NO   ,KC_NO   ,
        //├────────┼────────┼────────┼────────┼────────┼────────┼────────┤                         ├────────┼────────┼────────┼────────┼────────┼────────┼────────┤
           KC_TRNS ,KC_TRNS ,KC_TRNS ,KC_TRNS ,KC_TRNS ,KC_TRNS ,KC_F5   ,                          KC_TRNS ,KC_HOME ,KC_LEFT ,KC_DOWN ,KC_RGHT ,KC_END  ,KC_NO   ,
        //├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┐       ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
           KC_TRNS ,KC_TRNS ,KC_TRNS ,KC_TRNS ,KC_TRNS ,KC_TRNS ,KC_TRNS ,KC_TRNS ,        KC_TRNS ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_TRNS ,
        //├────────┼────────┼────────┼────────┼────┬───┴────┬───┼────────┼────────┤       ├────────┼────────┼───┬────┴───┬────┼────────┼────────┼────────┼────────┤
           KC_TRNS ,KC_TRNS ,KC_TRNS ,KC_TRNS ,     KC_LCTL ,    KC_SPC  ,L2_ENT  ,        KC_TRNS ,KC_TRNS ,    KC_TRNS ,     KC_TRNS ,KC_NO   ,KC_NO   ,KC_TRNS
        //└────────┴────────┴────────┴────────┘    └────────┘   └────────┴────────┘       └────────┴────────┘   └────────┘    └────────┴────────┴────────┴────────┘
           ),
	[_FLIP] = LAYOUT(
        //┌────────┬────────┬────────┬────────┬────────┬────────┐                                           ┌────────┬────────┬────────┬────────┬────────┬────────┐
           KC_NO   ,KC_6    ,KC_7    ,KC_8    ,KC_9    ,KC_0    ,                                            KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   , 
        //├────────┼────────┼────────┼────────┼────────┼────────┼────────┐                         ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┤
           KC_NO   ,KC_Y    ,KC_U    ,KC_I    ,KC_O    ,KC_P    ,KC_NO   ,                          KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,
        //├────────┼────────┼────────┼────────┼────────┼────────┼────────┐                         ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┤
           KC_NO   ,KC_H    ,KC_J    ,KC_K    ,KC_L    ,KC_SCLN ,KC_F9   ,                          KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   , 
        //├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┐       ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
           KC_LSFT ,KC_N    ,KC_M    ,KC_LBRC ,KC_QUOT ,KC_SLSH ,KC_TRNS ,KC_NO   ,        KC_NO   ,KC_TRNS ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   , 
        //├────────┼────────┼────────┼────────┼────┬───┴────┬───┼────────┼────────┤       ├────────┼────────┼───┬────┴───┬────┼────────┼────────┼────────┼────────┤
           KC_TRNS ,KC_TRNS ,KC_COMM ,KC_DOT  ,     KC_NO   ,    KC_NO   ,KC_TRNS ,        KC_NO   ,KC_NO   ,    KC_NO   ,     KC_TRNS ,KC_NO   ,KC_NO   , KC_TRNS
        //└────────┴────────┴────────┴────────┘    └────────┘   └────────┴────────┘       └────────┴────────┘   └────────┘    └────────┴────────┴────────┴────────┘
            ),
	[_FAUDIO] = LAYOUT(
        //┌────────┬────────┬────────┬────────┬────────┬────────┐                                           ┌────────┬────────┬────────┬────────┬────────┬────────┐
           RESET   ,KC_NO   ,KC_F10  ,KC_F11  ,KC_F12  ,KC_NO   ,                                            KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,RESET   , 
        //├────────┼────────┼────────┼────────┼────────┼────────┼────────┐                         ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┤
           KC_NO   ,KC_NO   ,KC_F7   ,KC_F8   ,KC_F9   ,KC_NO   ,NK_ON   ,                          KC_VOLU ,KC_NO   ,KC_MRWD ,KC_MFFD ,KC_NO   ,KC_NO   ,KC_NO   , 
        //├────────┼────────┼────────┼────────┼────────┼────────┼────────┐                         ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┤
           SF_GUI  ,KC_NO   ,KC_F4   ,KC_F5   ,KC_F6   ,KC_NO   ,NK_OFF  ,                          KC_VOLD ,KC_NO   ,KC_MPLY ,KC_MSTP ,KC_MUTE ,KC_NO   ,KC_NO   , 
        //├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┐       ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
           KC_TRNS ,KC_NO   ,KC_F1   ,KC_F2   ,KC_F3   ,KC_NO   ,KC_TRNS ,KC_NO   ,        KC_NO   ,KC_TRNS ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   , 
        //├────────┼────────┼────────┼────────┼────┬───┴────┬───┼────────┼────────┤       ├────────┼────────┼───┬────┴───┬────┼────────┼────────┼────────┼────────┤
           KC_TRNS ,KC_TRNS ,KC_TRNS ,KC_RGUI ,     KC_RCTL ,    KC_NO   ,KC_DEL   ,        KC_NO   ,KC_NO   ,    KC_NO   ,     KC_TRNS ,KC_NO   ,KC_NO   ,KC_TRNS
        //└────────┴────────┴────────┴────────┘    └────────┘   └────────┴────────┘       └────────┴────────┘   └────────┘    └────────┴────────┴────────┴────────┘
           ),
    [_RGBMOUSE] = LAYOUT(
        //┌────────┬────────┬────────┬────────┬────────┬────────┐                                           ┌────────┬────────┬────────┬────────┬────────┬────────┐
           RGB_SAI ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,                                            KC_NO   ,KC_ACL0 ,KC_ACL1 ,KC_ACL2 ,KC_NO   ,KC_NO   ,
        //├────────┼────────┼────────┼────────┼────────┼────────┼────────┐                         ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┤
           RGB_SAD ,RGB_M_X ,RGB_M_K ,RGB_M_R ,RGB_M_SW,RGB_TOG ,RGB_VAI ,                          KC_NO   ,KC_NO   ,KC_WH_L ,KC_MS_U ,KC_WH_R ,KC_NO   ,KC_NO   ,
        //├────────┼────────┼────────┼────────┼────────┼────────┼────────┐                         ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┤
           RGB_HUI ,RGB_M_B ,RGB_M_G ,RGB_M_P ,RGB_SPD ,RGB_SPI ,RGB_VAD ,                          KC_NO   ,KC_NO   ,KC_MS_L ,KC_MS_D ,KC_MS_R ,KC_NO   ,KC_NO   ,
        //├────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┐       ┌────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
           RGB_HUD ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,        KC_BTN3 ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,KC_NO   ,
        //├────────┼────────┼────────┼────────┼────┬───┴────┬───┼────────┼────────┤       ├────────┼────────┼───┬────┴───┬────┼────────┼────────┼────────┼────────┤
           KC_TRNS ,KC_NO   ,KC_NO   ,KC_TRNS ,     KC_NO   ,    KC_NO   ,KC_NO   ,        KC_BTN2 ,KC_BTN1 ,    KC_NO   ,     KC_TRNS ,KC_NO   ,KC_NO   ,KC_NO
        //└────────┴────────┴────────┴────────┘    └────────┘   └────────┴────────┘       └────────┴────────┘   └────────┘    └────────┴────────┴────────┴────────┘
           )
};

const rgblight_segment_t PROGMEM my_capslock_layer[] = RGBLIGHT_LAYER_SEGMENTS(
    {0, 2, HSV_RED}
);

const rgblight_segment_t PROGMEM my_numlock_layer[] = RGBLIGHT_LAYER_SEGMENTS(
    {12, 2, HSV_ORANGE}
);

const rgblight_segment_t PROGMEM my_gaming_layer[] = RGBLIGHT_LAYER_SEGMENTS(
    {0, 7, HSV_BLUE},
    {7, 7, HSV_BLACK}
);

const rgblight_segment_t PROGMEM my_flip_layer[] = RGBLIGHT_LAYER_SEGMENTS(
    {0, 7, HSV_PURPLE}
);


const rgblight_segment_t PROGMEM my_faudio_layer[] = RGBLIGHT_LAYER_SEGMENTS(
    {0, 14, HSV_SPRINGGREEN}
);


const rgblight_segment_t* const PROGMEM my_rgb_layers[] = RGBLIGHT_LAYERS_LIST(
    my_gaming_layer,
    my_capslock_layer,
    my_numlock_layer,
    my_faudio_layer,
    my_flip_layer
);

void keyboard_post_init_user(void) {
    // Enable the LED layers
    rgblight_layers = my_rgb_layers;
}

bool led_update_user(led_t led_state) {
    rgblight_set_layer_state(1, led_state.caps_lock); 
    rgblight_set_layer_state(2, led_state.num_lock); 
    return true;
}
layer_state_t layer_state_set_user(layer_state_t state) {
    rgblight_set_layer_state(0, layer_state_cmp(state, _GAME));    
    rgblight_set_layer_state(3, layer_state_cmp(state, _FAUDIO));    
    rgblight_set_layer_state(4, layer_state_cmp(state, _FLIP));    
    return state;
};
